baseURL           = "https://visuallydefine.com/"
title             = "Visually Define"
languageCode      = "en-us"
paginate          = 5
paginatePath      = "page"
disqusShortname   = "visuallydefine"
googleAnalytics   = "UA-113741959-2"

# GLOBALS
[params]
    description = "visuallydefine by avimehenwal"         # Max 160 characters show in search
    author      = "Avi Mehenwal"
    author_url  = "https://avimehenwal.in/"
    theme       = "brown"   # red, pink, purple,deep-purple,indigo,blue,cyan,teal, green,yelow,amber,orange,grey,brown
    hover       = "yellow"
    nav_bg      = "w3-teal"
    banner      = "VideoCameraHeadReadingBook3-300x268.jpg"  #"vd-banner-1.svg"
    subscribe   = "http://eepurl.com/dlqpQX"

# MENU-BAR
[[menu.sidebar]]
    name       = "Home"
    pre        = "<i class='fa fa-home'></i>"
    weight     = -110
    url        = "/"
[[menu.sidebar]]
    name       = "Quotes"
    pre        = "<i class='fa fa-pencil'></i>"
    post       = "<i class='fa fa-caret-down'></i>"
    weight     = 50
    identifier = "quote"
    url        = "/quote/"
[[menu.sidebar]]
    name       = "Vocabulary"
    pre        = "<i class='fa fa-book'></i>"
    post       = "<i class='fa fa-caret-down'></i>"
    weight     = 60
    identifier = "wortschatz"
    url        = "/wortschatz/"
[[menu.sidebar]]
    name       = "About Us"
    pre        = "<i class='fa fa-info-circle'></i>"
    weight     = 70
    identifier = "about"
    url        = "/about/info/"
[[menu.sidebar]]
    name       = "Experiments"
    pre        = "<i class='fa fa-magic'></i>"
    weight     = 79
    identifier = "experiments"
    url        = "/test/"
[[menu.sidebar]]
    name       = "Contact Us"
    pre        = "<i class='fa fa-comment'></i>"
    weight     = 80
    identifier = "contact-us"
    url        = "/contact-us/"
