baseURL = "https://visuallydefine.com/"
languageCode = "en-us"
title = "Visually Define"
sectionPagesMenu = "main"             # For lazy bloggers only sections
disqusShortname = "devopscreed"
googleAnalytics   = "UA-113741959-2"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home'></i>"
    weight = -110
    identifier = "home"
    url = "/"
# [[menu.main]]
#     name = "About"
#     pre = "<i class='fa fa-road'></i>"
#     weight = -100
#     url = "/"

[params]
    description = "visuallydefine by avimehenwal"         # Max 160 characters show in search
    author = "Avi Mehenwal"
    author_url = "https://avimehenwal.in/"
    theme = "green"   # red, pink, purple,deep-purple,indigo,blue,cyan,teal, green,yelow,amber,orange,grey,brown
    hover = "yellow"
    nav_bg = "w3-teal"
